INSERT INTO categories (id, name, description) VALUES (1, 'Sci-Fi', 'Science Fiction Bücher') ON CONFLICT DO NOTHING;
INSERT INTO categories (id, name, description) VALUES (2, 'Krimi', 'Kriminalromane') ON CONFLICT DO NOTHING;
INSERT INTO categories (id, name, description) VALUES (3, 'Roman', 'Klassische Romane') ON CONFLICT DO NOTHING;
INSERT INTO categories (id, name, description) VALUES (4, 'Fantasy', 'Fantasy Bücher') ON CONFLICT DO NOTHING;
INSERT INTO categories (id, name, description) VALUES (5, 'Biografie', 'Biografien und Autobiografien') ON CONFLICT DO NOTHING;
INSERT INTO categories (id, name, description) VALUES (6, 'Thriller', 'Spannende Thriller') ON CONFLICT DO NOTHING;
INSERT INTO categories (id, name, description) VALUES (7, 'Geschichte', 'Historische Bücher') ON CONFLICT DO NOTHING;
INSERT INTO categories (id, name, description) VALUES (8, 'Philosophie', 'Philosophische Werke') ON CONFLICT DO NOTHING;

INSERT INTO books (id, title, author, category_id) VALUES (1, 'Dune', 'Frank Herbert', 1) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (2, '1984', 'George Orwell', 1) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (3, 'Der Name der Rose', 'Umberto Eco', 2) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (4, 'Brave New World', 'Aldous Huxley', 1) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (5, 'The Martian', 'Andy Weir', 1) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (6, 'Enders Game', 'Orson Scott Card', 1) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (7, 'Neuromancer', 'William Gibson', 1) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (8, 'Das Parfum', 'Patrick Süskind', 2) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (9, 'Der Schwarm', 'Frank Schätzing', 2) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (10, 'Sherlock Holmes', 'Arthur Conan Doyle', 2) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (11, 'Die Verwandlung', 'Franz Kafka', 3) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (12, 'Der Prozess', 'Franz Kafka', 3) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (13, 'Faust', 'Johann Wolfgang von Goethe', 3) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (14, 'Die Leiden des jungen Werthers', 'Johann Wolfgang von Goethe', 3) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (15, 'Der Herr der Ringe', 'J.R.R. Tolkien', 4) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (16, 'Harry Potter', 'J.K. Rowling', 4) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (17, 'Das Lied von Eis und Feuer', 'George R.R. Martin', 4) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (18, 'Die Nebel von Avalon', 'Marion Zimmer Bradley', 4) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (19, 'Steve Jobs', 'Walter Isaacson', 5) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (20, 'Elon Musk', 'Walter Isaacson', 5) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (21, 'Long Walk to Freedom', 'Nelson Mandela', 5) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (22, 'Anne Frank Tagebuch', 'Anne Frank', 5) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (23, 'Das Bourne Identity', 'Robert Ludlum', 6) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (24, 'Gone Girl', 'Gillian Flynn', 6) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (25, 'The Girl with the Dragon Tattoo', 'Stieg Larsson', 6) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (26, 'Da Vinci Code', 'Dan Brown', 6) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (27, 'Sapiens', 'Yuval Noah Harari', 7) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (28, 'Der Untergang des Römischen Reiches', 'Edward Gibbon', 7) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (29, 'Krieg und Frieden', 'Leo Tolstoi', 7) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (30, 'Sein und Zeit', 'Martin Heidegger', 8) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (31, 'Also sprach Zarathustra', 'Friedrich Nietzsche', 8) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (32, 'Der Staat', 'Platon', 8) ON CONFLICT DO NOTHING;
INSERT INTO books (id, title, author, category_id) VALUES (33, 'Kritik der reinen Vernunft', 'Immanuel Kant', 8) ON CONFLICT DO NOTHING;
SELECT setval('books_id_seq', (SELECT MAX(id) FROM books));
SELECT setval('categories_id_seq', (SELECT MAX(id) FROM categories));